### ISSUE TITLE
TCP Time out (even after enabling it in settings.js

### ISSUE THREAD

**Issue by lipigab** [mental05/node-red-contrib-tplink-iot#12]
**Describe the bug**
my syslog is filling up with TCP Time out messages even after setting 15s in Node-Red's Setting.js

The following lines keep repeating:

TCP Timeout
Nov 12 23:23:40 RezedaPi Node-RED[30492]: [undefined] device.send() Error: TCP Timeout
Nov 12 23:23:40 RezedaPi Node-RED[30492]: (node:30492) UnhandledPromiseRejectionWarning: Error: TCP Timeout
Nov 12 23:23:40 RezedaPi Node-RED[30492]:     at Timeout._onTimeout (/home/pi/.node-red/node_modules/tplink-smarthome-api/lib/client.js:249:$
Nov 12 23:23:40 RezedaPi Node-RED[30492]:     at ontimeout (timers.js:498:11)
Nov 12 23:23:40 RezedaPi Node-RED[30492]:     at tryOnTimeout (timers.js:323:5)
Nov 12 23:23:40 RezedaPi Node-RED[30492]:     at Timer.listOnTimeout (timers.js:290:5)
Nov 12 23:23:40 RezedaPi Node-RED[30492]: (node:30492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated $

My Node-Red setting.js:

    // Retry time in milliseconds for TCP socket connections
    socketReconnectTime: 15000,

    // Timeout in milliseconds for TCP server socket connections
    //  defaults to no timeout
   socketTimeout: 15000,
 

I had to delete all the TP-Link nodes to stop the log filling up the SD card.

Can you please advise?
Many thanks,

**Comment by qwertangel** [comment]
same here.

**Comment by qwertangel** [comment]
I am wondering if you can change the node to accept negative value for polling interval. and use that to not poll at all ? that should solve it for people like me who are not interested in event notifications.

**Comment by lipigab** [comment]
I just gave it up and let Home Assistant control these bulbs. Since I can
interact with HA from Node Red, I can achieve the same things via this
way...

**Comment by GrantsPi** [comment]
Having the same problem; will watch here for a fix.

**Comment by qwertangel** [comment]
I am thinking of switching to direct tplink api - https://www.npmjs.com/package/tplink-smarthome-api

**Comment by qwertangel** [comment]
Here's the function node I created with tplink api. It controls two switches. Using msg property - room.

`const {Client} = global.get('tplink');
const client = new Client();

if (msg.room) {
    let ip = '192.168.x.x'; // living room
    if (msg.room === 'bedroom') {
        ip = '192.168.x.x1'; // bedroom
    }
    const plug = client.getDevice({host: ip}).then((device)=>{
        if (msg.brightness) {
            device.setPowerState(true);
            device.dimmer.setBrightness(msg.brightness);    
        } else {
            if (msg.payload && (typeof msg.payload === 'boolean')) { // if there is explicit action then on/off
                device.setPowerState(msg.payload);
            } else { // else just toggle
                device.togglePowerState();
            }
        }
     });
}
  
return msg;`

**Comment by rollischulze67** [comment]
With the code below, I succeeded to realize an own function node for a tp-link HS100 plug drectly with the tplink api. In this way, I can get and set the status of the plug and have no TCP Timeout-Messages anymore. In the API-documentation, the access on the plug-object was described as ".relayState ⇒ boolean".
But now I want to realize the same thing for a tp-link HS110 plug meter (or a LB120 bulb) where the structure of the object is more complicated as I have to access (sub-)obects in the plug meter object.
In the API-documentation, this is described as   ".getPowerState([sendOptions]) ⇒ Promise.<boolean, ResponseError>".

I tried a lot of days but didnt get it working.

Could anybody give me the code or a easy understandible code example how to solve the problem?
Help would be great.


const { Client } = global.get('My_tplink_API');
 
const client = new Client();

var relay_state = 0;

const plug = client.getPlug({ host: '192.168.XXX.XXX' });

//just get status
if (msg.payload === "getInfo")

{
    const plug = client.getDevice({ host: '192.168.XXX.XXX' }).then((device)=>{
        msg.payload = Number(device.relayState);
        node.send(msg);
        
     });
}   
    //plug has been activated
   else if (msg.payload === true)
    {
            plug.setPowerState(true);
            relay_state=1;
            msg.payload = relay_state;
            return msg;
            
    } else if (msg.payload === false)
        {
            plug.setPowerState(false);
            relay_state=0;
            msg.payload = relay_state;
            return msg;
        }
    
msg.payload = relay_state;
return;
